version: '3'

networks:
  reverse-proxy-network_reverse-proxy-network:
    external: true

services:
  reverse:
    container_name: reverse
    hostname: reverse
    image: nginx
    networks:
      - reverse-proxy-network_reverse-proxy-network
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/hugo/reverse-proxy/config:/etc/nginx
      - /home/hugo/reverse-proxy/certs:/etc/ssl/private
